

services:
  backend:
    build: ./backend_test
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

  frontend:
    build: ./frontend_test
    ports:
      - "80:80"
    depends_on:
      - backend